# Load config file
configfile: "workflow/config.yaml"


rule local_to_non_shared_fs:
    localrule: True
    output:
        f"<results>/write_local_fs.done",
    shell:
        """
        echo "{output}"
        mkdir -p $(dirname {output})
        touch {output}
        echo "write to test" > {output}
        """


# rule local_to_shared_fs:
#     localrule: True
#     output:
#         f'{config["PATH_SUBMIT_FS_OUTPUT"]}/write_submitfs.done',
#     shell:
#         """
#         echo "{output}"
#         mkdir -p $(dirname {output})
#         touch {output}
#         echo "write to test" > {output}
#         """


# rule submit_write_access_shared_fs:
#     output:
#         f'{config["PATH_SHARED_FS_OUTPUT"]}/write_sharedfs.done',
#     shell:
#         """
#         echo "{output}"
#         mkdir -p $(dirname {output})
#         touch {output}
#         echo "write to test" > {output}
#         """


# rule write_access_shared_fs:
#     localrule: True
#     output:
#         f'{config["PATH_SHARED_FS_OUTPUT"]}/read_sharedfs.done',
#     shell:
#         """
#         ls {config[PATH_SHARED_FS]} > /dev/null
#         echo "read access test" >> {output}
#         """


# rule test_path_parsing:
#     # showcase and test different ways to parse env variables in paths, see function at top of file
#     # tests interaction with string templating, such as f-strings, which can be tricky
#     localrule: True
#     output:
#         f'{config["PATH_SUBMIT_FS_OUTPUT"]}/hello.txt',
#     shell:
#         """
#         echo {config[PATH_SHARED_FS]} >> {output}
#         echo {config[PATH_SUBMIT_FS]} >> {output}
#         echo /cephfs/user/${{USER}}/snakemake_tests >> {output}
#         """


# rule copy_inputs_to_sharedfs:
#     localrule: True
#     input:
#         f"{workflow.workdir_init}/inputs/input.txt",
#     output:
#         f'{config["PATH_SHARED_FS_OUTPUT"]}/inputs/input.txt',
#     shell:
#         """
#         mkdir -p {config[PATH_SHARED_FS_OUTPUT]}/inputs
#         cp {input} {output}
#         """


# rule run_software:
#     input:
#         SOFT=rules.compile_software.output,
#         RUNT=rules.copy_setup_script_to_sharedfs.output,
#         INPUT=rules.copy_inputs_to_sharedfs.output,
#     output:
#         f'{config["PATH_SHARED_FS_OUTPUT"]}/out.txt',
#     params:
#         a=1,
#     shell:
#         """
#         . {input.RUNT} {input.SOFT}
#         mkdir run
#         cd run
#         main
#         cp {input.INPUT} .
#         cat output.txt >> input.txt
#         mkdir -p $(dirname {output[0]})
#         mv input.txt {output[0]}
#         cd ..
#         rm -r run
#         """
# rule all:
#     default_target: True
#     input:
#         rules.write_access_submit_fs.output,
#         rules.write_access_shared_fs.output,
#         rules.test_path_parsing.output,
#         rules.run_software.output,
#         rules.setupATLAS_local.output,
#         rules.setupATLAS_batch.output,
#         rules.test_input_tarball_to_workernode.output,
