# Load config file
configfile: "workflow/config.yaml"


# expand envvars in paths:
submit_inputs = os.path.expandvars(config["submit_inputs"])
submit_results = os.path.expandvars(config["submit_results"])


rule filter_str:
    input:
        config["input_data"],
    output:
        "ntuple0_str_output.root",
    log:
        "logs/filter/filter_str.log",
    params:
        input_tree_name="analysis",
        output_tree_name="analysis",
        criteria="(met >100)",
        branches_to_save=["met", "tau_pt"],
    threads: 2
    wrapper:
        "v9.3.0/phys/root/filter"
